FROM amazoncorretto:17-alpine-jdk //de qué impagen de java partimos
MAINTAINER LG //quién es el dueño
COPY  //copia el empaquetado y luego lo sube a github
ENTRYPOINT //la instrucción que se va a ejecutar primero
